env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.29.0
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - set -x;
    cargo fmt -- --check &&
    cargo test --verbose --release --features=testing &&
    cargo test --verbose --release --features=dump-graphs dot_parser &&
    cargo clippy --verbose --all-targets &&
    cargo clippy --verbose --all-targets --features=dump-graphs &&
    cargo clippy --verbose --all-targets --features=testing &&
    cargo clippy --verbose --all-targets --features=dump-graphs,testing &&
    cargo clippy --verbose --manifest-path=dot_gen/Cargo.toml
before_cache:
 - cargo prune
